# Generated by Django 4.2.7 on 2023-11-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, null=True)),
                ('antecedentes_patologicos', models.CharField(max_length=200)),
                ('antecedentes_quirurgicos', models.CharField(max_length=200)),
                ('rams', models.CharField(max_length=200)),
                ('relato_cronologico', models.CharField(max_length=200)),
                ('plan', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
